### ISSUE TITLE
v3.0 Beta test results - Download Station

### ISSUE THREAD

**Issue by wallacebrf** [007revad/Synology_app_mover#23]
Synology_app_mover v3.0.15
DS920+ DSM 7.2.1-69057-4

did not backup the` /volume1/@download` directory. 

This is where all of the in progress and completed downloads are kept. 

I would add a warning when backing up the - /volume1/@download directory that it could take a VERY long time depending on how many gigs or even TB are actively being downloaded and or seeded.

 perhaps add a question if the person wants to backup their downloads?

**Comment by 007revad** [comment]
The script checks the size of the `@docker` folder and the free space on the target volume. I'll make that check a function and use it for all extra folders. And warn that it could take a (long) while if the size is large.

I probably should ask if they want to backup the `@downloads` folder, but because it would take up double space until the `@downloads` folder is moved to the target volume it be better to:
1. Instead of moving the folder copy it to the target volume.
2. Then rename the source volume's `@downloads` to `@downloads_backup`.

I skipped moving the `@downloads` folder because mine is a few TB. But I don't how I forgot to include code to move it (and `@calendar`).

**Comment by 007revad** [comment]
Fixed in v3.0.19

**Comment by wallacebrf** [comment]
confirmed the red text warning that this could take a while

```
Stopping Download Station

Backing up /volume1/@appconf/DownloadStation
Backing up /volume1/@appdata/DownloadStation
Backing up /volume1/@apphome/DownloadStation
Backing up /volume1/@appshare/DownloadStation
Backing up /volume1/@appstore/DownloadStation
Backing up /volume1/@apptemp/DownloadStation

WARNING Moving @download could take a long time
Backing up /volume1/@download/DownloadStation

Starting Download Station

Finished backing up Download Station
```

**Comment by 007revad** [comment]
Nice. I haven't actually seen it myself.

Was the read text on the black background easy to read?

**Comment by wallacebrf** [comment]
> Nice. I haven't actually seen it myself.
> 
> Was the read text on the black background easy to read?

i thought so, it should at least be enough warning to people that the script is not stuck or something while working.
