### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by eudaldgr** [007revad/Synology_app_mover#39]
There's no stable release that include `@calendar` and the script doesn't change this file `/var/packages/Calendar/etc/share_link.json` `base_path` parameter

```json
{
   "SYNO.Cal.Application" : {
      "base_path" : "/volume1/@calendar/attach",
      "copy_from_nas_enable" : true,
      "quota_per_attach" : 20971520,
      "quota_per_attach_enable" : false,
      "quota_per_event" : 41943040
   }
}
```

and there's need to mv also `@synocalendar` for the core dumps, no config is needed to change in `/var/packages/Calendar/scripts/common` for this

```sh
[...]
synocal_db_dump_path="/${VOLUME}/@synocalendar/"
[...]
```

**Comment by 007revad** [comment]
v3 has been ready to be a stable release for a long while now. 

I've fixed both the issues you mentioned, in [v3.0.45](https://github.com/007revad/Synology_app_mover/releases/tag/v3.0.45).

I was only waiting because I had someone who was going to test moving, backing up and restoring every package and they were very helpful at first, but I haven't had any feedback from them in the last 6 weeks.
